SFD-3983 Etl Cloudwatch Alarms
nhsd-exeter/dos-service-fuzzy-search-api pull request #124
Opened 2022-01-31 08:02 UTC by gwaardenburg

2022-02-01 07:52 UTC, jope1 requested changes

2022-02-01 07:52 UTC, jope1 commented on infrastructure/stacks/service_etl/service_etl_sns.tf
> +resource "aws_cloudwatch_metric_alarm" "postcode_insert_alarm" {
typo - service_insert_alarm

2022-02-01 07:52 UTC, jope1 commented on infrastructure/stacks/service_etl/service_etl_sns.tf
> +  }
Can you add tags to this resource please?

2022-02-01 09:11 UTC, daonhs approved these changes

2022-02-01 09:26 UTC, ArifNhs submitted a review, later dismissed

2022-02-02 09:43 UTC, jope1 submitted a review, later dismissed

2022-02-02 10:58 UTC, ArifNhs approved these changes

2022-02-02 10:59 UTC, merged