SFD-4097 Mock external API calls
nhsd-exeter/dos-service-fuzzy-search-api pull request #125
Opened 2022-01-31 09:36 UTC by daonhs

2022-01-31 12:07 UTC, ArifNhs submitted a review, later dismissed

2022-02-01 10:18 UTC, jope1 requested changes

2022-02-01 10:18 UTC, jope1 commented on build/automation/var/profile/dev.mk
> +POSTCODE_MAPPING_SERVICE_URL := http://mockservice.sfs.test:8080/api
Is it possible to rename this URL so it's clearer what it is. Something like: mock.postcodeapi.sfs:8080/api ?

2022-02-01 10:18 UTC, jope1 commented on build/automation/var/profile/local.mk
> +POSTCODE_MAPPING_SERVICE_URL := http://mockservice.sfs.test:8080/api
Is it possible to rename this URL so it's clearer what it is. Something like: mock.postcodeapi.sfs:8080/api ?

2022-02-01 10:18 UTC, jope1 commented on build/docker/docker-compose.yml
> +          - mockservice.sfs.test
Is it possible to rename this URL so it's clearer what it is. Something like: mock.postcodeapi.sfs:8080/api ?

2022-02-01 10:18 UTC, jope1 commented on build/docker/docker-compose.yml
> +    container_name: mockservice
container_name: mock_postcodeapi ?

2022-02-01 10:18 UTC, jope1 commented on build/docker/docker-compose.yml
> +  mockservice:
mock_postcodeapi ?

2022-02-01 13:44 UTC, daonhs commented on build/automation/var/profile/dev.mk
> +POSTCODE_MAPPING_SERVICE_URL := http://mockservice.sfs.test:8080/api
Created new jira ticket for this requirement

2022-02-01 14:17 UTC, gwaardenburg approved these changes

2022-02-02 09:52 UTC, merged