Task/sfd 5602 enable fuzzy choices
nhsd-exeter/dos-service-fuzzy-search-api pull request #334
Opened 2023-11-22 09:22 UTC by sethaguda

2023-11-28 12:08 UTC, daonhs requested changes

2023-11-28 12:08 UTC, daonhs commented on build/automation/var/profile/local.mk
> +NHS_CHOICES_API_KEY := 7cc220dc7d134f8c906c2f7a1782a61fm
Please replace with a dummy key, this repo is not private

2023-11-28 12:08 UTC, daonhs commented on build/automation/var/profile/pd.mk
> +NHS_CHOICES_API_URL := MOCK_NHS_API_KEY
NHS_CHOICES_API_URL -> NHS_CHOICES_API_KEY

2023-12-06 16:30 UTC, daonhs submitted a review, later dismissed
Please review comments, theres a few sanity changes that needs to happen

2024-01-08 08:12 UTC, sethaguda commented on application/app/src/main/java/uk/nhs/digital/uec/api/config/ConcurrentSearchConfig.java
> +/*  @Bean
deleted

2024-01-08 08:14 UTC, sethaguda commented on build/automation/var/profile/pd.mk
> +NHS_CHOICES_API_URL := MOCK_NHS_API_KEY
changed

2024-01-08 08:19 UTC, sethaguda commented on application/app/src/main/java/uk/nhs/digital/uec/api/model/nhschoices/KeyValue.java
> +public class KeyValue {
deleted

2024-01-08 08:21 UTC, sethaguda commented on application/app/src/main/java/uk/nhs/digital/uec/api/model/nhschoices/Metric.java
> +public class Metric {
deleted

2024-01-08 08:22 UTC, sethaguda commented on application/app/src/main/java/uk/nhs/digital/uec/api/model/nhschoices/AgeRange.java
> +public class AgeRange {
deleted

2024-01-08 09:31 UTC, sethaguda commented on application/app/pom.xml
> +                      <minimum>60%</minimum>
refactored

2024-01-09 06:59 UTC, sethaguda commented on application/app/src/main/java/uk/nhs/digital/uec/api/model/ApiRequestParams.java
> +//@Scope(value = "request", proxyMode = ScopedProxyMode.TARGET_CLASS)
removed

2024-01-18 09:39 UTC, merged