SFD-2281 Service Data ETL
nhsd-exeter/dos-service-fuzzy-search-api pull request #56
Opened 2021-08-23 10:12 UTC by gwaardenburg

2021-08-23 10:18 UTC, ArifNhs submitted a review, later dismissed
Approved

2021-08-23 11:35 UTC, jope1 requested changes
Do we need all of the stuff under the stacks/dos-replica-etl/functions directory? Don't we just need the functions.zip file?

2021-08-23 11:35 UTC, jope1 commented on build/automation/var/platform-texas/v1/account-live-k8s-prod.mk
For prod, vars are:
TF_VAR_dos_replica_db := core-dos-sf-replica.dos-db-rds
TF_VAR_dos_security_group := live-lk8s-prod-uec-sf-core-dos-sf-replica-sg
TF_VAR_dos_read_replica_secret_name := core-dos/deployment
TF_VAR_ccg_etl_source_db := pathwaysdos

2021-08-23 11:35 UTC, jope1 commented on build/automation/var/profile/dev.mk
> +INFRASTRUCTURE_STACKS = elasticsearch,authentication,roles,dos_replcia_etl
Can we call the stack services_etl please?

2021-08-23 11:35 UTC, jope1 commented on infrastructure/stacks/dos_replica_etl/data.tf
> +data "archive_file" "dos_replica_etl_function" {
Lets do a general find and replace of 'dos-replica' to 'services'

2021-08-23 11:35 UTC, jope1 commented on infrastructure/stacks/dos_replica_etl/data.tf
> +data "aws_security_group" "dos_application_security_group" {
This is the service_finder_replica_sg can we change the name to reflect please?

2021-08-23 11:35 UTC, jope1 commented on infrastructure/stacks/dos_replica_etl/data.tf
> +  name = var.dos_security_group
Lets make this name clearer too please

2021-08-23 11:35 UTC, jope1 commented on infrastructure/stacks/dos_replica_etl/data.tf
> +data "aws_secretsmanager_secret" "dos_read_replica_secret_name" {
dos_sf_read_replica_secret_name

2021-08-23 11:35 UTC, jope1 commented on infrastructure/stacks/dos_replica_etl/dos_replica_etl.tf
> +      USR                = local.dos_replica_etl_db_user
Lets replace dos_replica with dos_sf_replica

2021-08-23 11:35 UTC, jope1 commented on infrastructure/stacks/dos_replica_etl/dos_replica_etl.tf
> +  description              = "allows lambda etl process to insert data into ES"
Update description:
"Allows SF Services ETL Lambda to access SF Elasticsearch datastore"

2021-08-23 11:35 UTC, jope1 commented on infrastructure/stacks/dos_replica_etl/variables.tf
> +variable "dos_replica_db" { description = "The DOS read replica to get the postcodes from" }
dos_sf_replica_db

2021-08-23 11:35 UTC, jope1 commented on infrastructure/stacks/dos_replica_etl/variables.tf
> +variable "dos_security_group" { description = "The security group for the dos read replica" }
dos_sf_replica_sg

2021-08-23 11:35 UTC, jope1 commented on infrastructure/stacks/dos_replica_etl/variables.tf
> +variable "dos_replica_etl_db_user" { description = "The dos read replica user name" }
services_etl_db_user

2021-08-23 11:35 UTC, jope1 commented on infrastructure/stacks/dos_replica_etl/variables.tf
> +variable "dos_replica_etl_source_db" { description = "The dos read replica source database" }
services_etl_source_db

2021-08-23 11:35 UTC, jope1 commented on infrastructure/stacks/dos_replica_etl/locals.tf
> +  dos_replica_etl_vpc_security_group       = data.aws_security_group.dos_application_security_group.id
dos_sf_replica_db_sg

2021-08-25 09:23 UTC, jope1 approved these changes

2021-08-25 09:27 UTC, merged